config/routes.rb
Captioner::Application.routes.draw do
  get "tags/show"
  devise_for :users
  get "home/index"

  root 'home#index'

  resources :submissions do
    resources :captions
  end
  resources :tags
  resources :charges

  get 'home/no_submit'
  

end

app/models/caption.rb
class Caption < ActiveRecord::Base
  has_attached_file :captioned_photo,
                  processors: [:captionbitch],
                  styles: -> (attachment) {
                      {
                      comic: {
                        format: '.png',
                        comic: true,
                        the_text: attachment.instance.text,
                        original_image: attachment.uploaded_file,
                        mask: Rails.root.join('public/mask.png')
                      }
                    }
                  } 

  belongs_to :submission
end

app/models/submission.rb
class Submission < ActiveRecord::Base
    # before_post_process :before_post_process

    # has_attached_file :photo, styles: { medium: "200x200^"}

    has_attached_file :photo,
                  processors: [:polarize],
                  styles: {
                    polarized: {
                      format: '.png',
                      is_polarized: true
                    }
                  } 


    # has_attached_file :photo, styles: { medium: "250x250>", thumb: "100x100>" }

    belongs_to :user
    has_many :captions
    validates :description, length: { minimum: 3}
    validates :photo, attachment_presence: { message: 'Make sure to attach a photo!'}

    has_and_belongs_to_many :tags

    def tag_names
      ''
    end

    def tag_names=(tags_string)
      tags_string.split(' ').each do |tag|
        new_tag = Tag.find_or_create_by(name: tag)
        new_tag.slug = new_tag.name.downcase
        new_tag.save
        
        self.tags << new_tag
      end
    end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :submissions

  def to_param
    slug
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


    has_many :submissions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end

end

app/controllers/captions_controller.rb
class CaptionsController < ApplicationController
  
  def index

  end

  def create
    
    this_submission =  Submission.find params[:submission_id]


    @caption = this_submission.captions.build params[:caption].permit(:text,:captioned_photo)
    @caption.captioned_photo = this_submission.photo
    @caption.save
    redirect_to request.referer
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_filter :authenticate_user!
  def new
  end

  def create
    # Amount in pennies
    @amount = 500

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'gbp'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @submissions = Submission.all
  end
  
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController


  def new
    @submission = Submission.new
  end

  def create

    @submission = current_user.submissions.build params[:submission].permit(:description, :photo, :tag_names)
    if @submission.save
      flash[:notice] = 'Photo added'
      redirect_to root_path
    else
      render 'new'
    end

  end

  def show
    @submission = Submission.find(params[:id])
    @deets = @submission.photo
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find_by slug: params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/submission_helper.rb
module SubmissionHelper

  def tag_names(submission)
    tag_links = submission.tags.map do |tag|
      link_to(tag.name, tag)
    end

    tag_links.join(", ").html_safe
  end



end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>£5.00</strong>!</h2>

<%= link_to 'Home', root_path %>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: £5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Buy your print!"
          data-amount="500"></script>
<% end %>

app/views/home/index.html.erb
<div class='row'>
  <div class='col-md-3'> 
      <% if user_signed_in? %>
        <p><%= "Hi, #{current_user.email}" %></p>
        <%= link_to 'Submit a photo', new_submission_path %>
      <% else %>
        <%= link_to 'Submit a photo', home_no_submit_path %> 
      <% end %>
  </div>

  <div class='col-md-9'>
  
  <% @submissions.each do |submission| %>


      <div class='col-md-3 pic-container'>
        <%= link_to (image_tag submission.photo.url(:polarized), class: 'uploaded-pic'), submission_path(submission) %>
        <p><%= link_to  submission.description, submission_path(submission) %></p> 
        <p>Submitted by <%= submission.user.email if submission.user %></p>
        <p><%= tag_names(submission) %></p>
        <p><%= link_to 'Buy print', new_charge_path %></p>
      </div>

    <% end %>
  </div>

</div>
  

app/views/home/no_submit.html.erb
    <p>You need to be logged in to submit a photo</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Captioner</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= nav_bar fixed: :top, brand: "Captioner - Let the world caption your photos " do %>
  <%= menu_group pull: :right do %>
    <% if user_signed_in? %>
      <%= menu_item 'Logout', destroy_user_session_path, :method => :delete %>
    <% else %>
      <%= menu_item 'Create account', new_user_registration_path %>
      <%= menu_item 'Sign in', new_user_session_path %>
    <% end %>
  <% end %>
<% end %>

<section class="wrapper">
  <%= bootstrap_flash %>
  <%= yield %>
</section>

<footer>
  <p>&copy; Captioner 2013</p>
</footer>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/submissions/new.html.erb
<p>Submit new photo</p>
 <%= bootstrap_flash %>
<%= form_for @submission, url: submissions_path, html: { multipart: true}  do |f| %>
  <%= f.label :photo %>
  <%= f.file_field :photo %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :tag_names, 'Tags' %>
  <%= f.text_field :tag_names %>

  <%= f.submit 'Save photo' %>

<% end %>

app/views/submissions/show.html.erb
<p>This is : <%= @submission.description%></p>

<%= image_tag @submission.photo.url(:polarized), class: 'uploaded-pic' %>

<%= form_for [@submission, Caption.new] do |f| %>
  <%= f.label :text, 'Enter a caption' %>
  <%= f.text_field :text%>
  <%= f.submit 'Add caption' %>
<% end %>

<% @submission.captions.each do |caption| %>
  <%= image_tag caption.captioned_photo.url(:comic), class: 'captioned_photo-pic',  alt: caption.text  %>

<% end %>

app/views/tags/show.html.erb
<h4><%= @tag.name %></h4>

<div class='row'>
  <% @tag.submissions.each do |submission| %>
    <div class='col-md-3 pic-container'>
      <%= image_tag submission.photo.url(:medium), class: 'uploaded-pic' %>
      <p><%= submission.description %></p> 
      <p>Submitted by <%= submission.user.email if submission.user %></p>
      <p><%= tag_names(submission) %></p>
    </div>
  <% end %>
</div>